# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [develop, feature/*]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-${{ matrix.node-version }}-pnpm-store
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js check
      - run: node common/scripts/install-run-rush.js rebuild --verbose
      - run: node common/scripts/install-run-rush.js test:coverage --verbose

env:
  CI: true
